inputSet:
  name: netcore-sample-app — dev
  identifier: netcore_sample_app_dev_inputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: netcore_sample_app_cd
    stages:
    - stage:
        identifier: deploy
        template:
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: netcore_sample_app_dev
                infrastructureDefinitions:
                - identifier: netcore_sample_app_dev_aks
              execution:
                steps:
                - step:
                    identifier: approvalBeforeSwap
                    type: HarnessApproval
                    spec:
                      approvers:
                        userGroups:
                        - account._organization_all_users
